config/routes.rb
Rails.application.routes.draw do
  resources :banks
  resources :suppliers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/dashboard", to: "dashboard#index"
  # get "/supplier/new", to: "suppliers#new"
  # post "/supplier", to: "supplier#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank.rb
class Bank < ApplicationRecord

  #=== Associations
  has_many :accounts, class_name: Bank::Accoun.name

  #=== Validations
  validates :name, presence: { message: I18n.t("bank.model.validate_empty")}
  validates :name, length: { maximum: 50, message: I18n.t("bank.model.validate_size") }

end

app/models/bank/accoun.rb
class Bank::Accoun < ApplicationRecord

  #=== Associations
  belongs_to :bank, class_name: Bank.name
  has_one :supplier, class_name: Supplier.name

  validates :number, presence: false, length: { maximum: 15 }
end

app/models/supplier.rb
class Supplier < ApplicationRecord

  #=== Associations
  belongs_to :accoun, class_name: Bank::Accoun.name
  accepts_nested_attributes_for :accoun

  #=== Validations
  validates :name, presence: { message: I18n.t("supplier.model.validate_empty_name")}
  validates :name_person_contact, presence: { message: I18n.t("supplier.model.validate_empty_name_person_contact")}
  validates :phone_person_contact, presence: false, length: { maximum: 10 }
  validates :nit, :'supplier/valid_nit' => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: %i[ show edit update destroy]
  before_action :set_locale!, only: %i[show edit update destroy]

  def set_locale!
    I18n.locale = :es
  end

  def index
    @banks = Bank.all
  end

  def show
  end

  def new
    @bank = Bank.new
  end

  def edit
  end

  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1 or /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully updated." }

      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /banks/1 or /banks/1.json
  def destroy
    @bank.destroy

    respond_to do |format|
      format.html { redirect_to banks_url, notice: "Bank was successfully destroyed." }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_params
      params.require(:bank).permit(:name)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

  end


end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[show edit update destroy]
  before_action :set_locale!

  def set_locale!
    I18n.locale = :es
  end

  def new
    @supplier = Supplier.new
    @supplier.build_accoun
    @banks = Bank.all
  end

  def show
  end

  def create
    @supplier = Supplier.new(supplier_params)
    respond_to do |format|
      if @supplier.save
        format.html { redirect_to supplier_url(@supplier), notice: "El proveedor fue creado exitosamente." }
      else
        format.html { render :new, status: :unprocessable_entity}
      end
    end
  end

  private
  def supplier_params
    params.require(:supplier).permit(:name, :nit, :name_person_contact, :phone_person_contact, accoun_attributes: [:number, :bank_id])
  end

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_bank.html.erb
<div id="<%= dom_id bank %>">
  <p>
    <strong><%=I18n.t("bank.name")%></strong>
    <%= bank.name %>
  </p>

</div>

app/views/banks/_form.html.erb
<%= form_with(model: bank) do |form| %>
  <% if bank.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bank.errors.count, "error")  %> <%= I18n.t("bank.error_save") %> </h2>

      <ul>
        <% bank.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render "form", bank: @bank %>

<br>

<div>
  <%= link_to "Show this bank", @bank %> |
  <%= link_to "Back to banks", banks_path %>
</div>

app/views/banks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= I18n.t("bank.index.title") %></h1>

<div id="banks" class="px-5 border">
  <% @banks.each do |bank| %>
    <%= render bank %>
    <p>
      <%= link_to I18n.t("bank.index.show"), bank %>
    </p>
  <% end %>
</div>

<div>
  <%= link_to I18n.t("bank.index.new"), new_bank_path %>
</div>

app/views/banks/new.html.erb
<h1>NUEVO BANCO</h1>
<div class="border">
<%= render "form", bank: @bank %>
</div>
<br>

<div>
  <%= link_to "Back to banks", banks_path %>
</div>

app/views/banks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bank %>

<div>
  <%= link_to "Edit this bank", edit_bank_path(@bank) %> |
  <%= link_to "Back to banks", banks_path %>

  <%= button_to "Destroy this bank", @bank, method: :delete %>
</div>

app/views/dashboard/index.html.erb
<h1 class="text-3xl font-bold underline">
  Hello world!
</h1>
<%= link_to "proveedor", new_supplier_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Htapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/supplier/new.html.erb
<h1>REGISTRAR PROVEEDOR Y CUENTA BANCARIA</h1>

<%#= render "form", bank: @bank %>

<%= form_for @supplier,  url: {controller: "supplier",  action: "create"} do |f| %>
  <%= f.label :nombre, style: "display: block" %>
  <%= f.text_field :name %>
  <%= f.label :nit, style: "display: block" %>
  <%= f.text_field :nit %>
  <%= f.label "persona de contacto", style: "display: block" %>
  <%= f.text_field :name_person_contact %>
  <%= f.label "celular persona de contacto", style: "display: block" %>
  <%= f.text_field :phone_person_contact %>
  <%= f.fields_for :accoun, Bank::Accoun.new do |accoun_form| %>
    <%= accoun_form.label "numero de cuenta", style: "display: block" %>
    <%= accoun_form.text_field :number %>
    <%= accoun_form.label "Banco", style: "display: block" %>
    <%= accoun_form.text_field :bank_id %>
    <% end %>
  <%= f.submit "Registrarte", class: " text-sm text-center bg-blue-300 text-white py-1 rounded font-medium" %>

<% end %>

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |f| %>
  <%= f.label I18n.t("supplier.model.attributes.name"), style: "display: block" %>
  <%= f.text_field :name %>
  <span class="flex items-center font-medium tracking-wide text-red-500 text-xs ml-1 mb-4"  style="color: red">
   <%= supplier.errors[:name].any? ? supplier.errors[:name].to_s[/\w([^"]*)/] : "" %>
  </span>
  <%= f.label :nit, style: "display: block" %>
  <%= f.text_field :nit, :value => nil %>
  <span class="flex items-center font-medium tracking-wide text-red-500 text-xs ml-1 mb-4" style="color: red">
    <%= supplier.errors[:nit].any? ? supplier.errors[:nit].to_s[/\w([^"]*)/] : ""  %>
  </span>
  <%= f.label "persona de contacto", style: "display: block" %>
  <%= f.text_field :name_person_contact %>
  <span class="flex items-center font-medium tracking-wide text-red-500 text-xs ml-1 mb-4"  style="color: red">
   <%= supplier.errors[:name_person_contact].any? ? supplier.errors[:name_person_contact].to_s[/\w([^"]*)/] : "" %>
  </span>
  <%= f.label "celular persona de contacto", style: "display: block" %>
  <%= f.text_field :phone_person_contact %>
  <span class="flex items-center font-medium tracking-wide text-red-500 text-xs ml-1 mb-4"  style="color: red">
   <%= supplier.errors[:phone_person_contact].any? ? supplier.errors[:phone_person_contact].to_s[/\w([^"]*)/] : "" %>
  </span>
  <%= f.fields_for :accoun, supplier.accoun do |accoun_form| %>
    <%= accoun_form.label "numero de cuenta", style: "display: block" %>
    <%= accoun_form.text_field :number %>
    <span class="flex items-center font-medium tracking-wide text-red-500 text-xs ml-1 mb-4"  style="color: red">
    <%= supplier.accoun.errors[:number].any? ? supplier.accoun.errors[:number].to_s[/\w([^"]*)/] : "" %>
    </span>
    <%= accoun_form.label "Banco", style: "display: block" %>
    <%=accoun_form.select :bank_id,  options_from_collection_for_select(banks, "id", "name"),
                          include_blank: 'Selecciona una opción' %>
    <span class="flex items-center font-medium tracking-wide text-red-500 text-xs ml-1 mb-4"  style="color: red">
    <%= supplier.accoun.errors[:bank].any? ? supplier.accoun.errors[:bank].to_s[/\w([^"]*)/] : "" %>
    </span>

  <% end %>
  <%= f.submit class: " text-sm text-center bg-blue-300 text-white py-1 rounded font-medium" %>

<% end %>

app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <p>
    <strong><%=I18n.t("bank.name")%></strong>
    <%= supplier.name %>
  </p>

</div>

app/views/suppliers/new.html.erb
<h1>REGISTRAR PROVEEDOR Y CUENTA BANCARIA</h1>
<div class="border">
  <%= render "form", supplier: @supplier, banks: @banks%>
</div>
<br>

<div>

</div>

app/views/suppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supplier %>

<div>
  <%= link_to "Edit this bank", edit_supplier_path(@supplier) %> |
  <%= link_to "Back to banks", supplier_path %>

  <%= button_to "Destroy this bank", @supplier, method: :delete %>
</div>